// Code generated by go generate; DO NOT EDIT.
// This file was generated by cmd/reset

package authenticate

import "sync"

func (r *authenticator) Reset() {
	if r == nil {
		return
	}

	r.hashType = ""

	r.hashHeaderKey = ""

	r.mu = sync.Mutex{}

}
