// Code generated by go generate; DO NOT EDIT.
// This file was generated by cmd/reset

package agent

func (r *Config) Reset() {
	if r == nil {
		return
	}

	r.Logger = nil

	r.ServerAddr = ""

	r.RateLimit = 0

	r.ReportTransport = ""

}

func (r *Options) Reset() {
	if r == nil {
		return
	}

	r.ServerAddress = ""

	r.Host = ""

	r.Port = ""

	r.Mode = ""

	r.HashKey = ""

	r.PollSec = 0

	r.ReportSec = 0

	r.RateLimit = 0

	r.ReportTransport = ""

}
