// Code generated by go generate; DO NOT EDIT.
// This file was generated by cmd/reset

package server

func (r *Options) Reset() {
	if r == nil {
		return
	}

	r.ServerAddress = nil

	r.StoreIntervalSec = nil

	r.HashKey = nil

	r.Host = ""

	r.Port = ""

	r.Mode = ""

	r.BackupStoragePath = ""

	r.DNS = ""

	r.AuditFile = ""

	r.AuditURL = ""

	r.Restore = false

}

func (r *Config) Reset() {
	if r == nil {
		return
	}

	r.logger = nil

	r.BackupConfig = nil

	r.scheme = ""

	r.host = ""

	r.port = ""

}
