// Code generated by go generate; DO NOT EDIT.
// This file was generated by cmd/reset

package metrics

func (r *CounterBackupStorage) Reset() {
	if r == nil {
		return
	}

}

func (r *GaugeBackupStorage) Reset() {
	if r == nil {
		return
	}

}
