package reset

import (
	"os"
	"path/filepath"
	"strings"
	"text/template"

	"golang.org/x/tools/imports"
)

const (
	ExtGoGen     = "reset.gen.go"
	TemplateName = "reset.template"
)
const (
	TypeInt   = "int"
	TypeUint  = "uint"
	TypeFloat = "float"
)
const templateStr = `
// Code generated by go generate; DO NOT EDIT.
// This file was generated by cmd/reset

package {{.Package}}
	{{range .Structs}}
		func (r *{{.Name}}) Reset() {
			if r == nil {
				return
			}
			{{range .Fields}}
				{{if eq .Type "pointer"}}
					r.{{.Name}} = nil
				{{else if eq .Type "map"}}
					clear(r.{{.Name}})
				{{else if eq .Type "slice"}}
					r.{{.Name}} = r.{{.Name}}[:0]
				{{else if eq .TypeName "sync.Mutex"}}
					r.{{.Name}} = sync.Mutex{}
				{{else if eq .TypeName "string"}}
					r.{{.Name}} = ""
				{{else if eq .TypeName "bool"}}
					r.{{.Name}} = false
				{{else if isInt .TypeName}}
					r.{{.Name}} = 0
				{{end}}
			{{end}}
		}
{{end}}`

var funcs = template.FuncMap{
	"isInt": func(v string) bool {
		return strings.HasPrefix(v, TypeInt) ||
			strings.HasPrefix(v, TypeUint) ||
			strings.HasPrefix(v, TypeFloat)
	},
}

var tmpl = template.Must(template.New(TemplateName).Funcs(funcs).Parse(templateStr))

func GenerateFile(dir string, data *PackageData) {
	src := executeTemplate(data)
	formatted := formatWithImports(dir, src)

	err := os.WriteFile(filepath.Join(dir, ExtGoGen), formatted, 0644)
	if err != nil {
		panic(err)
	}
}

func executeTemplate(data *PackageData) []byte {
	var sb strings.Builder
	if err := tmpl.Execute(&sb, data); err != nil {
		panic(err)
	}
	return []byte(sb.String())
}

func formatWithImports(dir string, src []byte) []byte {
	out, err := imports.Process(filepath.Join(dir, ExtGoGen), src, nil)
	if err != nil {
		panic(err)
	}
	return out
}
