// Code generated by go generate; DO NOT EDIT.
// This file was generated by cmd/reset

package observer

func (r *MetricsEvent) Reset() {
	if r == nil {
		return
	}

	r.IP = ""

	r.Metrics = r.Metrics[:0]

	r.TS = 0

}
