// Code generated by go generate; DO NOT EDIT.
// This file was generated by cmd/reset

package agent

import "sync"

func (r *Agent) Reset() {
	if r == nil {
		return
	}

	r.collector = nil

	r.reporter = nil

	r.ReportPool = nil

	r.mu = sync.Mutex{}

}

func (r *Collector) Reset() {
	if r == nil {
		return
	}

	clear(r.Gauges)

	clear(r.Counters)

	r.collectorPool = nil

	r.updaterPool = nil

	r.mu = sync.Mutex{}

}

func (r *Request) Reset() {
	if r == nil {
		return
	}

	r.ID = ""

	r.MType = ""

	r.Value = ""

}

func (r *Response) Reset() {
	if r == nil {
		return
	}

	r.Result = ""

	r.Code = 0

}

func (r *Reporter) Reset() {
	if r == nil {
		return
	}

	r.httpClient = nil

	r.logger = nil

	r.serverAddr = ""

}
