// Code generated by go generate; DO NOT EDIT.
// This file was generated by cmd/reset

package agent

import "sync"

func (r *Agent) Reset() {
	if r == nil {
		return
	}

	r.collector = nil

	r.sender = nil

	r.ReportPool = nil

	r.mu = sync.Mutex{}

}

func (r *Collector) Reset() {
	if r == nil {
		return
	}

	clear(r.Gauges)

	clear(r.Counters)

	r.collectorPool = nil

	r.updaterPool = nil

	r.mu = sync.Mutex{}

}
