// Code generated by go generate; DO NOT EDIT.
// This file was generated by cmd/reset

package middleware

func (r *signingResponseWriter) Reset() {
	if r == nil {
		return
	}

	r.buf = nil

	r.statusCode = 0

}
