// Code generated by go generate; DO NOT EDIT.
// This file was generated by cmd/reset

package file

import "sync"

func (r *Config) Reset() {
	if r == nil {
		return
	}

	r.Logger = nil

	r.StoragePath = ""

	r.filePath = ""

	r.Enabled = false

}

func (r *BackupHandler) Reset() {
	if r == nil {
		return
	}

	r.reader = nil

	r.writer = nil

}

func (r *BackupService) Reset() {
	if r == nil {
		return
	}

	r.BackupStorage = nil

	r.mu = sync.Mutex{}

}

func (r *MetricBackupStorage) Reset() {
	if r == nil {
		return
	}

	r.Writer = nil

	r.Reader = nil

}

func (r *Writer) Reset() {
	if r == nil {
		return
	}

	r.file = nil

	r.writer = nil

}
