// Code generated by go generate; DO NOT EDIT.
// This file was generated by cmd/reset

package db

func (r *Tx) Reset() {
	if r == nil {
		return
	}

}

func (r *DB) Reset() {
	if r == nil {
		return
	}

}
