// Code generated by go generate; DO NOT EDIT.
// This file was generated by cmd/reset

package config

func (r *ServerAddress) Reset() {
	if r == nil {
		return
	}

	r.Full = ""

	r.Host = ""

	r.Port = ""

}
