// Code generated by go generate; DO NOT EDIT.
// This file was generated by cmd/reset

package metrics

func (r *Gauge) Reset() {
	if r == nil {
		return
	}

}

func (r *Metrics) Reset() {
	if r == nil {
		return
	}

	r.ID = ""

	r.MType = ""

	r.Delta = nil

	r.Value = nil

	r.Hash = ""

}
