// Code generated by go generate; DO NOT EDIT.
// This file was generated by cmd/reset

package postgres

import "sync"

func (r *Config) Reset() {
	if r == nil {
		return
	}

	r.conn = nil

	r.initialized = false

}

func (r *Handler) Reset() {
	if r == nil {
		return
	}

	r.dbConn = nil

}

func (r *MetricStorage) Reset() {
	if r == nil {
		return
	}

	r.Config = nil

	r.mu = sync.Mutex{}

}
